ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS additional_phone VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_viber BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_whatsapp BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_signal BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS education VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profession VARCHAR(255);
