-- Seed/refresh role_requirements for membership progression.
-- Idempotent: rerunnable safely in production.

INSERT INTO role_requirements (
  role,
  role_level,
  display_name_uk,
  description_uk,
  requires_contribution,
  min_contribution_amount,
  min_direct_referrals,
  min_direct_referrals_at_role,
  min_total_referrals,
  min_helped_advance,
  helped_advance_from_role,
  helped_advance_to_role,
  privileges,
  updated_at
) VALUES
  (
    'supporter',
    0,
    'Прихильник',
    'Зареєстрований користувач без внеску. Отримує розсилку новин.',
    FALSE,
    NULL,
    0,
    NULL,
    0,
    0,
    NULL,
    NULL,
    '["newsletter"]'::jsonb,
    NOW()
  ),
  (
    'candidate',
    1,
    'Кандидат в члени',
    'Зробив внесок від 49 грн. Може голосувати на праймеріз.',
    TRUE,
    4900,
    0,
    NULL,
    0,
    0,
    NULL,
    NULL,
    '["newsletter","primary_voting"]'::jsonb,
    NOW()
  ),
  (
    'member',
    2,
    'Член Мережі',
    'Залучив 2 кандидатів. Повні права голосування.',
    FALSE,
    NULL,
    2,
    'candidate',
    0,
    0,
    NULL,
    NULL,
    '["newsletter","primary_voting","full_voting","events","tasks"]'::jsonb,
    NOW()
  ),
  (
    'honorary_member',
    3,
    'Почесний Член',
    '2 залучених стали Членами. Доступ до програми лояльності.',
    FALSE,
    NULL,
    0,
    NULL,
    0,
    2,
    'candidate',
    'member',
    '["newsletter","primary_voting","full_voting","events","tasks","loyalty_program"]'::jsonb,
    NOW()
  ),
  (
    'network_leader',
    4,
    'Лідер Мережі',
    '8 особистих рефералів + 49 в дереві. Право на номінацію, доступ до Ради Лідерів.',
    FALSE,
    NULL,
    8,
    'candidate',
    49,
    0,
    NULL,
    NULL,
    '["newsletter","primary_voting","full_voting","events","tasks","loyalty_program","nomination","leaders_council"]'::jsonb,
    NOW()
  ),
  (
    'regional_leader',
    5,
    'Регіональний лідер',
    'Допоміг 6 Почесним Членам стати Лідерами + 400 загальних. Пріоритет на номінацію мера.',
    FALSE,
    NULL,
    0,
    NULL,
    400,
    6,
    'honorary_member',
    'network_leader',
    '["newsletter","primary_voting","full_voting","events","tasks","loyalty_program","nomination","leaders_council","mayor_priority"]'::jsonb,
    NOW()
  ),
  (
    'national_leader',
    6,
    'Національний лідер',
    'Допоміг 4 Лідерам стати Регіональними + 4000 загальних. Пріоритет на депутата/президента.',
    FALSE,
    NULL,
    0,
    NULL,
    4000,
    4,
    'network_leader',
    'regional_leader',
    '["newsletter","primary_voting","full_voting","events","tasks","loyalty_program","nomination","leaders_council","mayor_priority","mp_priority","president_priority"]'::jsonb,
    NOW()
  ),
  (
    'network_guide',
    7,
    'Провідник Мережі',
    'Допоміг 2 Регіональним стати Національними + 25000 загальних. Контроль 70% бюджету.',
    FALSE,
    NULL,
    0,
    NULL,
    25000,
    2,
    'regional_leader',
    'national_leader',
    '["newsletter","primary_voting","full_voting","events","tasks","loyalty_program","nomination","leaders_council","mayor_priority","mp_priority","president_priority","budget_control"]'::jsonb,
    NOW()
  )
ON CONFLICT (role) DO UPDATE
SET
  role_level = EXCLUDED.role_level,
  display_name_uk = EXCLUDED.display_name_uk,
  description_uk = EXCLUDED.description_uk,
  requires_contribution = EXCLUDED.requires_contribution,
  min_contribution_amount = EXCLUDED.min_contribution_amount,
  min_direct_referrals = EXCLUDED.min_direct_referrals,
  min_direct_referrals_at_role = EXCLUDED.min_direct_referrals_at_role,
  min_total_referrals = EXCLUDED.min_total_referrals,
  min_helped_advance = EXCLUDED.min_helped_advance,
  helped_advance_from_role = EXCLUDED.helped_advance_from_role,
  helped_advance_to_role = EXCLUDED.helped_advance_to_role,
  privileges = EXCLUDED.privileges,
  updated_at = NOW();
